spring:
  application:
    name: ridepulse-backend
    profiles:
      active: prod

  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
    username: postgres.jisovgdcjdqmmzzmysru
    password: gesPup-kabpop-donpi6
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 0

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Colombo

  task:   # ✅ FIXED (moved here)
    execution:
      thread-name-prefix: prediction-

server:
  port: ${PORT:8080}

app:
  jwt:
    secret: ridepulse-super-secret-key-change-in-production-must-be-32-chars-min
    expiration-ms: 86400000

logging:
  level:
    com.ridepulse: DEBUG
    org.springframework.security: INFO

lstm:
  service:
    url: https://ridepulse.onrender.com
    enabled: true